<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{978cad62-4036-4e47-9e8a-459f7b1451b8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSimCell		: FB_SimCell;
	Seed			: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Seed := Seed + 1;
fbSimCell();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="17" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>