<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Filler" Id="{6295f515-0cbf-4a9e-9a05-3f3e3f3d6db2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Filler IMPLEMENTS IStation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Busy" Id="{7b22d881-ebdb-4f3f-befe-dc51dc54aaa2}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{ca417ef2-f1af-4039-b554-114d2928bdf1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Execute" Id="{ff5674ff-bdfb-419d-a54e-f90304492f60}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Execute : PVOID
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Faulted" Id="{2979689c-56ae-45ad-889c-8947b962ccd6}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Faulted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{ac2e006c-b510-42e2-8be1-91884283522f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Ready" Id="{0c567ab7-f2cc-4ae2-bbee-7022ed467954}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Ready : BOOL
]]></Declaration>
      <Get Name="Get" Id="{c6abe93d-9dd7-495c-9228-987f2d612abd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Filler">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Filler.Busy.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Filler.Execute">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Filler.Faulted.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Filler.Ready.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>